<?php

return[
    [
        "title"=>"Characters",
        "href"=>"/"
    ],
    [
        "title"=>"Comics",
        "href"=>"#"
    ],
    [
        "title"=>"Movies",
        "href"=>"#"
    ],
    [
        "title"=>"Tv",
        "href"=>"#"
    ],
    [
        "title"=>"Games",
        "href"=>"#"
    ],
    [
        "title"=>"Collectionables",
        "href"=>"#"
    ],
    [
        "title"=>"Videos",
        "href"=>"#"
    ],
    [
        "title"=>"Fans",
        "href"=>"#"
    ],
    [
        "title"=>"News",
        "href"=>"#"
    ],
    [
        "title"=>"Shop",
        "href"=>"#"
    ]
];